LLM_USER_SUBTYPE_XMLID = "llm_mail_message_subtypes.mt_llm_user"
LLM_ASSISTANT_SUBTYPE_XMLID = "llm_mail_message_subtypes.mt_llm_assistant"
LLM_TOOL_RESULT_SUBTYPE_XMLID = "llm_mail_message_subtypes.mt_llm_tool_result"
