{
    "name": "Easy AI Chat",
    "summary": "Simple AI Chat for Odoo",
    "description": """
Easy AI Chat for Odoo
=====================
A user-friendly module that brings AI-powered chat to your Odoo environment. Integrate with multiple AI providers, manage real-time conversations, and enhance workflows with multimodal support.
    """,
    "category": "Productivity, Discuss",
    "version": "16.0.1.0.0",
    "depends": ["base", "mail", "web", "llm"],
    "author": "Apexive Solutions LLC",
    "website": "https://github.com/apexive/odoo-llm",
    "external_dependencies": {"python": ["emoji"]},
    "data": [
        "security/llm_thread_security.xml",
        "security/ir.model.access.csv",
        "views/llm_thread_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "llm_thread/static/lib/marked/marked.min.js",
            "llm_thread/static/src/utils/markdown_utils.js",
            # Models
            "llm_thread/static/src/models/main.js",
            "llm_thread/static/src/models/messaging.js",
            "llm_thread/static/src/models/llm_chat.js",
            "llm_thread/static/src/models/llm_chat_view.js",
            "llm_thread/static/src/models/thread.js",
            "llm_thread/static/src/models/composer.js",
            "llm_thread/static/src/models/composer_view.js",
            "llm_thread/static/src/models/llm_model.js",
            "llm_thread/static/src/models/llm_provider.js",
            "llm_thread/static/src/models/thread_view.js",
            "llm_thread/static/src/models/llm_chat_thread_header_view.js",
            "llm_thread/static/src/models/chatter.js",
            # Components
            "llm_thread/static/src/components/llm_chat/llm_chat.js",
            "llm_thread/static/src/components/llm_chat/llm_chat.xml",
            "llm_thread/static/src/components/llm_chat_thread_list/llm_chat_thread_list.js",
            "llm_thread/static/src/components/llm_chat_thread_list/llm_chat_thread_list.xml",
            "llm_thread/static/src/components/llm_chat_thread/llm_chat_thread.js",
            "llm_thread/static/src/components/llm_chat_thread/llm_chat_thread.scss",
            "llm_thread/static/src/components/llm_chat_thread/llm_chat_thread.xml",
            "llm_thread/static/src/components/llm_chat_container/llm_chat_container.js",
            "llm_thread/static/src/components/llm_chat_container/llm_chat_container.xml",
            "llm_thread/static/src/components/llm_chat_container/llm_chat_container.scss",
            "llm_thread/static/src/components/llm_chat_sidebar/llm_chat_sidebar.js",
            "llm_thread/static/src/components/llm_chat_sidebar/llm_chat_sidebar.xml",
            "llm_thread/static/src/components/llm_chat_sidebar/llm_chat_sidebar.scss",
            "llm_thread/static/src/components/llm_chat_composer/llm_chat_composer.js",
            "llm_thread/static/src/components/llm_chat_composer/llm_chat_composer.xml",
            "llm_thread/static/src/components/llm_chat_composer/llm_chat_composer.scss",
            "llm_thread/static/src/components/llm_chat_composer_text_input/llm_chat_composer_text_input.js",
            "llm_thread/static/src/components/llm_chat_composer_text_input/llm_chat_composer_text_input.xml",
            "llm_thread/static/src/components/llm_chat_composer_text_input/llm_chat_composer_text_input.scss",
            "llm_thread/static/src/components/llm_chat_message_list/llm_chat_message_list.js",
            "llm_thread/static/src/components/llm_chat_message_list/llm_chat_message_list.xml",
            "llm_thread/static/src/components/llm_chat_thread_header/llm_chat_thread_header.js",
            "llm_thread/static/src/components/llm_chat_thread_header/llm_chat_thread_header.xml",
            "llm_thread/static/src/components/llm_chat_thread_header/llm_chat_thread_header.scss",
            "llm_thread/static/src/components/llm_chatter_topbar/llm_chatter_topbar.xml",
            "llm_thread/static/src/components/llm_chatter_topbar/llm_chat_topbar.scss",
            "llm_thread/static/src/components/llm_chatter/llm_chatter.xml",
            # Client Actions
            "llm_thread/static/src/llm_chat_client_action.js",
            # Styles
            (
                "after",
                "web/static/src/scss/pre_variables.scss",
                "llm_thread/static/src/components/llm_chat/llm_chat.scss",
            ),
            (
                "after",
                "web/static/src/scss/pre_variables.scss",
                "llm_thread/static/src/components/llm_chat_thread_list/llm_chat_thread_list.scss",
            ),
        ],
    },
    "license": "LGPL-3",
    "installable": True,
    "application": True,
    "auto_install": False,
}
